{{- if .Values.webapp.active }}
    {{- $name := "webapp-session" -}}
    {{- $port := 8002 -}}
    {{- $command := print "pip install agentbuddy==" .Values.webapp.vesion " && python -m agentbuddy.session.app" -}}
    {{- $params := dict "name" $name "command" $command "podTemplates" .Values.webapp.podTemplates "port" $port -}}
    {{ include "pod-deploy.tpl" $params }}
    {{- (printf "---") }}
    {{ include "pod-service.tpl" $params }}
{{ end -}}