apiVersion: v1
kind: Pod
metadata:
  name: isp-cv-expert
  labels:
    app: isp-cv-expert
spec:
  containers:
    - name: isp-cv-expert
      image: python:3.12
      command:
        [
          "sh",
          "-c",
          "pip install fastapi uvicorn pydantic requests pymemgpt==0.3.21 && python app.py",
        ]
      env:
        - name: MEMGPT_BASEURL
          value: "http://my-memgpt:8083"
        - name: AGENT_NAME
          value: "isp-cv-expert"
        - name: PERSONA_NAME
          value: "isp-cv-expert"
      volumeMounts:
        - name: code-volume
          mountPath: /app.py
          subPath: agent.py
        - name: code-utils-volume
          mountPath: /utils/memgpt.py
          subPath: memgpt.py
        - name: code-agent-volume
          mountPath: /agent/app.py
          subPath: app.py
  volumes:
    - name: code-volume
      configMap:
        name: agent-code
    - name: code-utils-volume
      configMap:
        name: utils-memgpt
    - name: code-agent-volume
      configMap:
        name: agent-app

---
apiVersion: v1
kind: Service
metadata:
  name: isp-cv-expert
spec:
  selector:
    app: isp-cv-expert
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
