apiVersion: v1
kind: Pod
metadata:
  name: isp-hr-expert
  labels:
    app: isp-hr-expert
spec:
  containers:
    - name: isp-hr-expert
      image: 2mmanu/agentbuddy:latest
      command:
        [
          "sh",
          "-c",
          "python /app.py",
        ]
      env:
        - name: MEMGPT_BASEURL
          value: "http://my-memgpt:8083"
        - name: AGENT_NAME
          value: "isp-hr-expert"
        - name: PERSONA_NAME
          value: "isp-hr-expert"
        - name: AGENT_PURPOSE
          value: "HR Assistant: Description: HR Assistant provides information regarding salaries, benefits, compensation policies, and other HR-related issues, helping to determine a competitive and appropriate salary offer. Example questions: - 'What is an appropriate starting salary for the candidate?' - 'What benefits and extra compensation can the candidate expect?' - 'What is the standard salary range for this position in our company?'"
        - name: AGENT_HOST
          value: "isp-hr-expert"
        - name: AGENT_PORT
          value: "80"
        - name: AGENT_P_HOST
          value: "facilitator"
        - name: AGENT_P_PORT
          value: "80"
      volumeMounts:
        - name: code-volume
          mountPath: /app.py
          subPath: agent.py
        - name: code-utils-volume
          mountPath: /utils/memgpt.py
          subPath: memgpt.py
        - name: code-agent-volume
          mountPath: /agent/app.py
          subPath: app.py
  volumes:
    - name: code-volume
      configMap:
        name: agent-code
    - name: code-utils-volume
      configMap:
        name: utils-memgpt
    - name: code-agent-volume
      configMap:
        name: agent-app

---
apiVersion: v1
kind: Service
metadata:
  name: isp-hr-expert
spec:
  selector:
    app: isp-hr-expert
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
