global:
  memgpt:
    host: "http://my-memgpt:8083"
    key: "sk-3865e0a0f8f2fb976a7856d40c1df573dec09e537cae95ad"

webapp:
  active: true
  vesion: 0.1.1.dev7 
  podTemplates:
    env:
    - name: TWIN_BASE_URL
      value: "http://digital-twin:8005"
    - name: SESSION_BASE_URL
      value: "http://webapp-session:8002"
    #TODO user e short per be
    - name: USER_NAME
      value: Emmanuele
    - name: USER_SHORT
      value: "vivo a Torino"

twin:
  version: 0.1.1.dev7
  podTemplates:
    env:
    - name: FACILITATOR_BASE_URL
      value: "http://facilitator/api/v1"
    - name: MEMGPT_BASE_URL
      value: "http://my-memgpt:8083"
    - name: MEMGPT_KEY
      value: "sk-fa5c7de8d6c03bdb29a5efe5fe3fbacbdbd31fb341e4dccf"
    - name: SESSION_BASE_URL
      value: "http://webapp-session:8002"

facilitators:
  - name: "facilitator"
    podTemplates:
      replicaCount: 1

domains:
  - name: "hr-domain"
    agents:
      - name: "isp-hr-expert"
        parent: "facilitator"
        info:
          agentDescription: |
              HR Assistant provides information regarding salaries, benefits, compensation policies, 
              and other HR-related issues, helping to determine a competitive and appropriate salary offer. 
          exampleQuestions: | 
              - What is an appropriate starting salary for the candidate?
              - What benefits and extra compensation can the candidate expect?
              - What is the standard salary range for this position in our company?
  - name: "cv-domain"
    agents:
      - name: "isp-cv-expert"
        parent: "facilitator"
        info:
          agentDescription: |
            CV Assistant manages candidates' resumes and provides detailed information about them, 
            such as their work experience, education, and references. 
          exampleQuestions: | 
            - Who is the candidate and do we have their resume? 
            - Can you provide me with a copy of the candidate's resume? 
            - What are the candidate's past work experiences?