# https://www.krakend.io/docs/deploying/kubernetes/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend-deployment
spec:
  selector:
    matchLabels:
      app: krakend
  replicas: 1
  template:
    metadata:
      labels:
        app: krakend
    spec:
      containers:
      - name: krakend
        image: devopsfaith/krakend:2.7.0
        ports:
        - containerPort: 8080
        imagePullPolicy: Never
        command: [ "/usr/bin/krakend" ]
        args: [ "run", "-d", "-c", "/configs/krakend.json", "-p", "8080" ]
        # securityContext:
          # allowPrivilegeEscalation: false
          # runAsNonRoot: true
          # runAsUser: 1000
          # readOnlyRootFilesystem: true
          # capabilities:
          #   drop:
          #     - ALL
          #   add:
          #     - NET_BIND_SERVICE
        env:
        - name: KRAKEND_PORT
          value: "8080"
        volumeMounts:
        - name: config-volume
          mountPath: /configs/krakend.json
          subPath: krakend.json
      volumes:
        - name: config-volume
          configMap:
            name: krakend-config
